# Generated by Django 4.2.8 on 2024-08-17 07:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("webchat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="participants",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
