# Generated by Django 4.2.8 on 2024-08-18 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webchat', '0003_chatroom_remove_message_conversation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chatroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='webchat.chatroom'),
        ),
    ]
